const roles = {
  Admin: [
    "admin_dashboard",
    "getUsers",
    "getUser",
    "deleteUser",
    "deleteCourse",
    "getCourses",
    "getTeachers",
    "getTeacher",
    "getChildren",
    "getChild",
    "getTeacherByGrade",
    "getCoursesByGrade",
    "getCoursesByTeacher",
  ],
  Teacher: [
    "teacher_dashboard",
    "uploadCourse",
    "updateCourse",
    "deleteCourse",
    "getCourses",
    "downloadCourse",
    "getTeachers",
    "getChild",
    "getTeacher",
    "getTeacherByGrade",
    "getCoursesByGrade",
    "getCoursesByTeacher",
  ],
  Parent: [
    "parent_dashboard",
    "enrollCourse",
    "getCourses",
    "getCoursesByGrade",
    "getCoursesByTeacher",
    "getCourse",
    "downloadCourse",
    "getTeachers",
    "getTeacher",
    "getChildren",
    "getParentChildren",
    "getChild",
    "getTeacherByGrade",
    "addChild",
  ],
};

module.exports = roles;
